version: '3'
services:

  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: lbaw2235
      POSTGRES_PASSWORD: yavmJBXK
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: lbaw2235@lbaw.com
      PGADMIN_DEFAULT_PASSWORD: yavmJBXK
    ports:
      - "4321:80"
    depends_on:
      - postgres

